# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-06-14T19:11:07+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Mode(Enum):
    """
    async (201, queue consolidation) or sync (200, consolidate inline).
    """

    async_ = 'async'
    sync = 'sync'


class Role(Enum):
    """
    The turn's author role: system, user, or assistant.
    """

    system = 'system'
    user = 'user'
    assistant = 'assistant'


class AddMemoryRequest(BaseModel):
    """
    One turn to append (api-design §3). ``turn_id`` optional — server-mints a ULID.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    content: str = Field(..., description='The turn text to remember.', title='Content')
    event_time: AwareDatetime | None = Field(
        None,
        description='When the turn occurred (aware UTC); defaults to now.',
        title='Event Time',
    )
    infer: bool | None = Field(
        True,
        description='When false, store the turn raw with NO consolidation job enqueued.',
        title='Infer',
    )
    metadata: dict[str, Any] | None = Field(
        None,
        description='Client metadata stored on the turn for filtering.',
        title='Metadata',
    )
    mode: Mode | None = Field(
        'async',
        description='async (201, queue consolidation) or sync (200, consolidate inline).',
        title='Mode',
    )
    role: Role = Field(
        ...,
        description="The turn's author role: system, user, or assistant.",
        title='Role',
    )
    session_id: str | None = Field(
        None, description='Client session overlay label.', title='Session Id'
    )
    turn_id: str | None = Field(
        None,
        description='Client/ULID turn id; supplied makes the write retry-safe (ON CONFLICT).',
        title='Turn Id',
    )
    user_id: str | None = Field(
        None, description='Client user partition label.', title='User Id'
    )


class Role1(Enum):
    system = 'system'
    user = 'user'
    assistant = 'assistant'


class BatchMessage(BaseModel):
    """
    One message in a mem0-style batch (api-design §3).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    content: str = Field(..., title='Content')
    role: Role1 = Field(..., title='Role')
    turn_id: str | None = Field(
        None, description='Optional per-message client id.', title='Turn Id'
    )


class BodyResourcesRememberResourceFile(BaseModel):
    blob_ref: str = Field(
        ...,
        description="Opaque handle to the blob in the caller's store.",
        title='Blob Ref',
    )
    file: str = Field(
        ...,
        description='The image to caption and embed.',
        json_schema_extra={'contentMediaType': 'application/octet-stream'},
        title='File',
    )
    session_id: str | None = Field(
        None, description='Client session overlay label.', title='Session Id'
    )
    user_id: str | None = Field(
        None, description='Client user partition label.', title='User Id'
    )


class CompressRequest(BaseModel):
    """
    The scope (and budget) for a whole-user panel-summary digest (api-design §3).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: str | None = Field(
        None, description='Client session overlay label.', title='Session Id'
    )
    token_budget: int | None = Field(
        2000,
        description='Approximate token budget for the packed digest.',
        title='Token Budget',
    )
    user_id: str | None = Field(
        None, description='Client user partition label.', title='User Id'
    )


class CompressResponse(BaseModel):
    """
    The 200 compress body: the packed panel-summary digest as one block.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    digest: str = Field(
        ...,
        description='The newest-first panel summaries packed under the budget.',
        title='Digest',
    )


class ConsolidateRequest(BaseModel):
    """
    The scope a consolidation runs over — flat user/session, at least one (§2).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: str | None = Field(
        None, description='Client session overlay label.', title='Session Id'
    )
    user_id: str | None = Field(
        None, description='Client user partition label.', title='User Id'
    )


class FactCorrectionRequest(BaseModel):
    """
    The bi-temporal correction body for a fact edge (api-design §3 Item ops).

    Carries the flat scope (``_ScopedBody``: at least one of user/session, a missing
    pair is the boundary 422) plus the new ``object`` the fact should now assert. The
    subject/relation are NOT settable — a correction keeps the same predicate and only
    revises its value (a different subject/relation is a new fact, not a correction).
    ``confidence`` and ``t_valid`` are optional, defaulting in ``ops.update_fact`` (the
    latter to now), and both are validated there before any DB round-trip or paid embed.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    confidence: float | None = Field(
        1.0,
        description='Confidence of the corrected edge, a [0,1] probability.',
        title='Confidence',
    )
    object: str = Field(
        ...,
        description='The corrected object the fact should now assert.',
        title='Object',
    )
    session_id: str | None = Field(
        None, description='Client session overlay label.', title='Session Id'
    )
    t_valid: AwareDatetime | None = Field(
        None,
        description='When the correction becomes valid (aware UTC); defaults to now.',
        title='T Valid',
    )
    user_id: str | None = Field(
        None, description='Client user partition label.', title='User Id'
    )


class FactItem(BaseModel):
    """
    The corrected fact edge in the flat wire shape (its new ``ft_`` id + text).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    confidence: float = Field(
        ..., description="The corrected edge's confidence.", title='Confidence'
    )
    id: str = Field(
        ..., description="The successor edge's public id (ft_<uuid>).", title='Id'
    )
    t_valid: AwareDatetime = Field(
        ..., description='When the corrected edge became valid.', title='T Valid'
    )
    text: str = Field(
        ...,
        description="The regenerated 'subject relation object' fact text.",
        title='Text',
    )
    type: str | None = Field(
        'fact', description="Always 'fact' for this surface.", title='Type'
    )


class FilterOp(Enum):
    eq = 'eq'
    ne = 'ne'
    in_ = 'in'
    gte = 'gte'
    lte = 'lte'
    gt = 'gt'
    lt = 'lt'


class ForesightItem(BaseModel):
    """
    A surfaced forward-looking note (plan / temporary state / deadline).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    content: str = Field(
        ..., description='The forward-looking note text.', title='Content'
    )
    id: str = Field(
        ...,
        description='Prefixed public id of the source episode (ep_<uuid>).',
        title='Id',
    )
    kind: str = Field(
        ..., description='plan, temporary_state, or deadline.', title='Kind'
    )


class ForgetResponse(BaseModel):
    """
    The 200 forget body: per-kind counts of what the cascade erased.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    facts_deleted: int = Field(..., title='Facts Deleted')
    foresight_deleted: int = Field(..., title='Foresight Deleted')
    tesserae_deleted: int = Field(..., title='Tesserae Deleted')
    turns_deleted: int = Field(..., title='Turns Deleted')


class Status(Enum):
    ok = 'ok'
    unavailable = 'unavailable'


class HealthStatus(BaseModel):
    """
    The liveness/readiness body: a single machine-readable status token.
    """

    status: Status = Field(..., title='Status')


class Status1(Enum):
    """
    Coarse lifecycle state.
    """

    queued = 'queued'
    running = 'running'
    succeeded = 'succeeded'
    failed = 'failed'


class JobStatusResponse(BaseModel):
    """
    The coarse job-status body an SDK polls (api-design §3).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    created_at: AwareDatetime = Field(
        ..., description='When the job was enqueued.', title='Created At'
    )
    error: str | None = Field(
        None, description='The last error, if the job failed.', title='Error'
    )
    id: str = Field(..., description='The public job id (job_<int>).', title='Id')
    kind: str = Field(..., description='The job kind (e.g. consolidate).', title='Kind')
    status: Status1 = Field(..., description='Coarse lifecycle state.', title='Status')
    updated_at: AwareDatetime = Field(
        ..., description='When the job last transitioned.', title='Updated At'
    )


class Type(Enum):
    """
    The memory's type.
    """

    episode = 'episode'
    fact = 'fact'


class MemoryItem(BaseModel):
    """
    One browsed/fetched memory in the flat typed wire shape (api-design §2).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    created_at: AwareDatetime = Field(
        ..., description='When the record was created.', title='Created At'
    )
    id: str = Field(
        ...,
        description='Prefixed public id (ep_<uuid> for an episode, ft_<uuid> a fact).',
        title='Id',
    )
    metadata: dict[str, Any] | None = Field(
        None, description='Stored client metadata.', title='Metadata'
    )
    text: str = Field(
        ..., description='The episode narrative or the fact text.', title='Text'
    )
    type: Type = Field(..., description="The memory's type.", title='Type')


class PageMemoryItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    has_more: bool = Field(
        ..., description='Whether a further page exists.', title='Has More'
    )
    items: list[MemoryItem] = Field(
        ..., description='The items on this page.', title='Items'
    )
    next_cursor: str | None = Field(
        None,
        description='Opaque cursor for the next page; null when there are no more.',
        title='Next Cursor',
    )


class PinResponse(BaseModel):
    """
    The pin/unpin result: the target state plus whether this call changed it.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    changed: bool = Field(
        ...,
        description='False when the episode was already in this state (or unknown).',
        title='Changed',
    )
    id: str = Field(..., description="The episode's public id (ep_<uuid>).", title='Id')
    pinned: bool = Field(
        ...,
        description='The protected state after the call (True=pinned).',
        title='Pinned',
    )


class ProblemDetail(BaseModel):
    """
    An RFC-9457 ``application/problem+json`` body — the one error shape (api-design §5).

    Every non-2xx response serializes to this so an SDK has a single error model to
    generate against. ``type``/``title``/``status`` are the RFC core members;
    ``detail`` is the human-readable, SANITIZED explanation (never an internal stack
    or a raw provider message for a 5xx). ``instance`` carries the request's
    correlation id so a caller can quote it when reporting a failure. The model is
    declared as a ``response_model`` on every route's ``responses={…}`` map so it
    shows up in the committed OpenAPI artifact.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    detail: str | None = Field(
        None,
        description='A human-readable, sanitized explanation of this occurrence.',
        title='Detail',
    )
    instance: str | None = Field(
        None,
        description='The request correlation id (X-Request-Id) for this occurrence.',
        title='Instance',
    )
    status: int = Field(
        ..., description='The HTTP status code for this occurrence.', title='Status'
    )
    title: str = Field(
        ...,
        description='A short, human-readable summary of the problem type.',
        title='Title',
    )
    type: str | None = Field(
        'about:blank',
        description="A URI identifying the problem type; 'about:blank' for generic errors.",
        title='Type',
    )


class ProcedureView(BaseModel):
    """
    A stored/recalled procedure in the wire shape (its ``ep_`` id + reinforcement).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description="The procedure's public id (ep_<uuid>, a tessera subtype).",
        title='Id',
    )
    last_outcome: bool | None = Field(
        None,
        description='The most recent recorded outcome, or null if never applied.',
        title='Last Outcome',
    )
    steps: list[str] = Field(..., description='The ordered steps.', title='Steps')
    success: str = Field(..., description='The success cue.', title='Success')
    trigger: str = Field(
        ..., description="The skill's trigger / recall key.", title='Trigger'
    )
    uses: int = Field(
        ..., description='How many times the procedure has been applied.', title='Uses'
    )


class Provenance(BaseModel):
    """
    The read-path provenance: how the context was routed, verified, and repaired (§3).

    All three are null on the pure P0 path (no hot client wired): ``route`` is the
    difficulty the router assigned, ``verifier`` whether the hard-path verifier judged
    the context sufficient (the PRE-repair verdict that triggered any repair), and
    ``repaired`` whether one targeted repair round ran.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    repaired: bool | None = Field(
        False, description='Whether one repair round ran.', title='Repaired'
    )
    route: str | None = Field(
        None, description="The router's difficulty label.", title='Route'
    )
    verifier: bool | None = Field(
        None,
        description="The hard-path verifier's pre-repair sufficiency verdict.",
        title='Verifier',
    )


class Mode1(Enum):
    """
    chat (full surface + hot router/verifier) or reasoning (lean, no LLM).
    """

    chat = 'chat'
    reasoning = 'reasoning'


class RecallProceduresRequest(BaseModel):
    """
    A task to recall learned skills for, by trigger similarity (api-design §3).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    k: int | None = Field(
        3, description='Maximum number of procedures to return.', title='K'
    )
    min_similarity: float | None = Field(
        None,
        description='Drop matches below this cosine similarity; null keeps top-k.',
        title='Min Similarity',
    )
    session_id: str | None = Field(
        None, description='Client session overlay label.', title='Session Id'
    )
    task: str = Field(
        ...,
        description='The task to match against stored procedure triggers.',
        title='Task',
    )
    user_id: str | None = Field(
        None, description='Client user partition label.', title='User Id'
    )


class RecallResourcesRequest(BaseModel):
    """
    A text query to recall resources for, by caption/visual similarity (api-design §3).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    k: int | None = Field(
        5, description='Maximum number of resources to return.', title='K'
    )
    query: str = Field(
        ..., description='The text to match against resource captions.', title='Query'
    )
    session_id: str | None = Field(
        None, description='Client session overlay label.', title='Session Id'
    )
    user_id: str | None = Field(
        None, description='Client user partition label.', title='User Id'
    )


class RecalledProcedure(BaseModel):
    """
    One recalled procedure paired with its trigger-match similarity (best-first).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    procedure: ProcedureView = Field(
        ..., description='The recalled skill and its reinforcement state.'
    )
    similarity: float = Field(
        ...,
        description='Cosine similarity of the task to the trigger (larger is nearer).',
        title='Similarity',
    )


class RecordOutcomeRequest(BaseModel):
    """
    The application outcome to record against a procedure (api-design §3).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: str | None = Field(
        None, description='Client session overlay label.', title='Session Id'
    )
    success: bool = Field(
        ..., description='Whether applying the procedure succeeded.', title='Success'
    )
    user_id: str | None = Field(
        None, description='Client user partition label.', title='User Id'
    )


class ReindexResponse(BaseModel):
    """
    The 200 reindex report: derived-state repair counts (deterministic, no LLM).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    panels_refreshed: int = Field(
        ...,
        description='Level-0 panels whose centroid was recomputed.',
        title='Panels Refreshed',
    )
    turns_backfilled: int = Field(
        ...,
        description='Raw turns whose null embedding was backfilled.',
        title='Turns Backfilled',
    )


class RememberProcedureRequest(BaseModel):
    """
    A how-to skill to store (api-design §3): trigger, ordered steps, success cue.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: str | None = Field(
        None, description='Client session overlay label.', title='Session Id'
    )
    steps: list[str] = Field(
        ..., description='The ordered steps that accomplish the skill.', title='Steps'
    )
    success: str = Field(
        ..., description='How the agent knows the skill worked.', title='Success'
    )
    trigger: str = Field(
        ...,
        description='What the skill is for — the recall key (embedded).',
        title='Trigger',
    )
    user_id: str | None = Field(
        None, description='Client user partition label.', title='User Id'
    )


class RememberResourceRequest(BaseModel):
    """
    A blob handle (+ caption or captionable URL) to store (api-design §3).

    The caller owns the blob store; ``blob_ref`` is the opaque handle Tessera persists.
    Supply ``caption`` to store it verbatim, or ``image_url`` to have the VLM caption a
    fetchable image. Exactly which is required is enforced downstream by
    ``resource.remember_resource`` (a missing-both case asks the VLM with no image and
    surfaces as a ``ValueError`` → 422).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    blob_ref: str = Field(
        ...,
        description="Opaque handle to the blob in the caller's store.",
        title='Blob Ref',
    )
    caption: str | None = Field(
        None,
        description='A caller-supplied caption; omit to VLM-caption image_url.',
        title='Caption',
    )
    image_url: str | None = Field(
        None,
        description='A fetchable image URL the VLM captions when caption is omitted.',
        title='Image Url',
    )
    mime: str = Field(
        ..., description="The blob's MIME type (e.g. image/png).", title='Mime'
    )
    session_id: str | None = Field(
        None, description='Client session overlay label.', title='Session Id'
    )
    user_id: str | None = Field(
        None, description='Client user partition label.', title='User Id'
    )


class ResourceItem(BaseModel):
    """
    A stored/recalled resource in the wire shape (its ``ep_`` id + caption + handle).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    blob_ref: str = Field(
        ..., description='The opaque blob handle the caller resolves.', title='Blob Ref'
    )
    caption: str = Field(
        ..., description='The searchable caption (the episode text).', title='Caption'
    )
    id: str = Field(
        ...,
        description="The resource's public id (ep_<uuid>, a tessera subtype).",
        title='Id',
    )
    mime: str = Field(..., description="The blob's MIME type.", title='Mime')


class Type1(Enum):
    episode = 'episode'
    fact = 'fact'


class Type2(Enum):
    """
    The hit's type.
    """

    episode = 'episode'
    fact = 'fact'


class SearchResult(BaseModel):
    """
    One flat, typed search hit (api-design §3, §7 — ``score``, never ``similarity``).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., description='Prefixed public id (ep_<uuid> or ft_<uuid>).', title='Id'
    )
    score: float = Field(
        ...,
        description='The fused (or reranked) relevance score, best first.',
        title='Score',
    )
    text: str = Field(
        ..., description='The episode narrative or fact text.', title='Text'
    )
    type: Type2 = Field(..., description="The hit's type.", title='Type')


class TypedResult(BaseModel):
    """
    One typed retrieval hit echoed alongside the composed context (api-design §3).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., description='Prefixed public id (ep_<uuid> or ft_<uuid>).', title='Id'
    )
    score: float = Field(
        ..., description='The fused (or reranked) relevance score.', title='Score'
    )
    text: str = Field(
        ..., description='The episode narrative or fact text.', title='Text'
    )
    type: Type2 = Field(..., description="The hit's type.", title='Type')


class WipeRequest(BaseModel):
    """
    The body for a whole-user wipe — scope (and only scope) in the body (api-design §3).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: str | None = Field(
        None, description='Client session overlay label.', title='Session Id'
    )
    user_id: str | None = Field(
        None, description='Client user partition label.', title='User Id'
    )


class WipeResponse(BaseModel):
    """
    The 200 wipe body: the total rows erased across every table (right-to-be-forgotten).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    total: int = Field(
        ...,
        description='Total rows erased across all tables for the user.',
        title='Total',
    )


class FieldScopedBody(BaseModel):
    """
    The flat scope every write/wipe body carries: at least one of user/session (§2).

    ``user_id`` and ``session_id`` are client partition labels (NOT authenticated — the
    tenant is); ``scoping.resolve_owner`` rejects the empty pair with the boundary 422.
    Declared here so the writes share one definition of the scope fields rather than
    redeclaring them per body.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: str | None = Field(
        None, description='Client session overlay label.', title='Session Id'
    )
    user_id: str | None = Field(
        None, description='Client user partition label.', title='User Id'
    )


class TesseraApiV1MaintenanceConsolidationSummary(BaseModel):
    """
    The flat consolidation counts an inline (``?sync=true``) run returns.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    facts_created: int = Field(..., title='Facts Created')
    foresight_created: int = Field(..., title='Foresight Created')
    llm_calls: int = Field(..., title='Llm Calls')
    tesserae_created: int = Field(..., title='Tesserae Created')
    turns_consolidated: int = Field(..., title='Turns Consolidated')


class TesseraApiV1MaintenanceJobHandle(BaseModel):
    """
    The pollable handle to an enqueued consolidate job (api-design §3).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description='Public job id (job_<int>) to poll at GET /v1/jobs/{id}.',
        title='Id',
    )
    status: str = Field(
        ..., description='Coarse job status at enqueue time.', title='Status'
    )


class TesseraApiV1MemoriesConsolidationSummary(BaseModel):
    """
    The flat consolidation counts a sync write returns (a thin view of the report).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    facts_created: int = Field(..., title='Facts Created')
    foresight_created: int = Field(..., title='Foresight Created')
    llm_calls: int = Field(..., title='Llm Calls')
    tesserae_created: int = Field(..., title='Tesserae Created')
    turns_consolidated: int = Field(..., title='Turns Consolidated')


class TesseraApiV1MemoriesJobHandle(BaseModel):
    """
    The pollable handle to the consolidation job an async write enqueued (or null).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        description='Public job id (job_<int>) to poll at GET /v1/jobs/{id}.',
        title='Id',
    )
    status: str = Field(
        ..., description='Coarse job status at enqueue time.', title='Status'
    )


class AsyncAddResponse(BaseModel):
    """
    The 201 async-write body: turn durable now, consolidation queued in the background.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    consolidation_queued: bool = Field(
        ...,
        description='Whether this write enqueued a consolidation.',
        title='Consolidation Queued',
    )
    created: bool = Field(
        ...,
        description='False when an idempotent re-add matched an existing turn.',
        title='Created',
    )
    job: TesseraApiV1MemoriesJobHandle | None = Field(
        None,
        description='The enqueued job handle, or null when the cadence did not fire.',
    )
    turn_id: str = Field(
        ...,
        description="The turn's client/ULID id, durable and queryable now.",
        title='Turn Id',
    )


class BatchAddRequest(BaseModel):
    """
    A mem0-style batch of turns appended sequentially under one scope (api-design §3).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    infer: bool | None = Field(
        True, description='Per-turn consolidation-enqueue toggle.', title='Infer'
    )
    messages: list[BatchMessage] = Field(
        ..., description='The turns to append, in order.', title='Messages'
    )
    metadata: dict[str, Any] | None = Field(
        None, description='Metadata for every turn.', title='Metadata'
    )
    mode: Literal['async'] = Field(
        'async',
        description='Batch writes are async only (a batch of inline consolidations is unbounded).',
        title='Mode',
    )
    session_id: str | None = Field(
        None, description='Client session overlay label.', title='Session Id'
    )
    user_id: str | None = Field(
        None, description='Client user partition label.', title='User Id'
    )


class BatchAddResponse(BaseModel):
    """
    The 201 batch body: one async-add result per message, in request order.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    results: list[AsyncAddResponse] = Field(
        ..., description='Per-message add results, in order.', title='Results'
    )


class EnqueuedResponse(BaseModel):
    """
    The 202 body: the consolidate job was queued for the background worker.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    job: TesseraApiV1MaintenanceJobHandle = Field(
        ..., description='The enqueued (or already-active) consolidate job.'
    )


class FilterClause(BaseModel):
    """
    One request-side read predicate, mapping straight onto the domain ``Filter``.

    The wire shape of ``store.repos.filters`` input: ``field`` is an intrinsic column
    (``importance``, ``event_time``, …) or ``metadata.<key>``; ``op`` is the
    ``FilterOp`` enum; ``value`` is the bound comparand. Validation of the field name
    and operator against the per-arm whitelist happens in the compiler (which raises
    ``ValidationError`` → 422), NOT here — duplicating the whitelist on the wire model
    would create a second source of truth that could drift from the SQL-safe one.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    field: str = Field(
        ..., description="An intrinsic column name or 'metadata.<key>'.", title='Field'
    )
    op: FilterOp = Field(..., description='The comparison operator.')
    value: Any = Field(
        ..., description='The comparand bound as a SQL parameter.', title='Value'
    )


class QueryRequest(BaseModel):
    """
    The composed-read query (api-design §3). Scope is the flat user/session pair (§2).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    as_of: AwareDatetime | None = Field(
        None,
        description="VALID-time vantage on the facts arm ('what was true then').",
        title='As Of',
    )
    filters: list[FilterClause] | None = Field(
        None,
        description='ANDed read predicates on the episode/fact arms.',
        title='Filters',
    )
    known_as_of: AwareDatetime | None = Field(
        None,
        description="TRANSACTION-time vantage on the facts arm ('what the store believed then').",
        title='Known As Of',
    )
    mode: Mode1 | None = Field(
        'chat',
        description='chat (full surface + hot router/verifier) or reasoning (lean, no LLM).',
        title='Mode',
    )
    query: str = Field(
        ..., description='The question to compose a memory context for.', title='Query'
    )
    session_id: str | None = Field(
        None, description='Client session overlay label.', title='Session Id'
    )
    top_k: int | None = Field(
        None,
        description='Episode breadth; defaults to the configured knn_k.',
        title='Top K',
    )
    user_id: str | None = Field(
        None, description='Client user partition label.', title='User Id'
    )


class QueryResponse(BaseModel):
    """
    The composed-read body: the context primary plus its structured pieces (api-design §3).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    context: str = Field(
        ...,
        description='The composed, prompt-ready memory context (the primary).',
        title='Context',
    )
    episodes: list[TypedResult] = Field(
        ..., description='The episode hits alone.', title='Episodes'
    )
    facts: list[TypedResult] = Field(
        ..., description='The fact hits alone.', title='Facts'
    )
    foresight: list[ForesightItem] = Field(
        ..., description='Surfaced forward-looking notes (chat).', title='Foresight'
    )
    portrait: dict[str, Any] | None = Field(
        None,
        description='The user portrait (chat mode only), or null.',
        title='Portrait',
    )
    provenance: Provenance = Field(
        ..., description='Read-path route/verifier/repair provenance.'
    )
    results: list[TypedResult] = Field(
        ..., description='The typed episode/fact hits, by score.', title='Results'
    )


class RecallProceduresResponse(BaseModel):
    """
    The recall envelope: matched procedures, highest similarity first (api-design §3).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    results: list[RecalledProcedure] = Field(
        ..., description='Matched procedures, best-first.', title='Results'
    )


class RecalledResource(BaseModel):
    """
    One recalled resource paired with its similarity (best-first).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    resource: ResourceItem = Field(..., description='The recalled resource.')
    similarity: float = Field(
        ...,
        description='Cosine similarity to the query (larger = nearer).',
        title='Similarity',
    )


class SearchRequest(BaseModel):
    """
    The structured-read query (api-design §3). Scope is the flat user/session pair (§2).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    as_of: AwareDatetime | None = Field(
        None,
        description="VALID-time vantage on the facts arm ('what was true then').",
        title='As Of',
    )
    filters: list[FilterClause] | None = Field(
        None,
        description='ANDed read predicates (intrinsic columns / metadata.<key>).',
        title='Filters',
    )
    known_as_of: AwareDatetime | None = Field(
        None,
        description="TRANSACTION-time vantage on the facts arm ('what the store believed then').",
        title='Known As Of',
    )
    query: str = Field(
        ...,
        description='The search text (embedded on both retrieval tiers).',
        title='Query',
    )
    rerank: bool | None = Field(
        True,
        description='Whether to apply the configured reranker (off ⇒ raw RRF order).',
        title='Rerank',
    )
    session_id: str | None = Field(
        None, description='Client session overlay label.', title='Session Id'
    )
    top_k: int | None = Field(
        None,
        description='Episode breadth; defaults to the configured knn_k.',
        title='Top K',
    )
    types: list[Type1] | None = Field(
        None, description='Restrict results to these types; null ⇒ both.', title='Types'
    )
    user_id: str | None = Field(
        None, description='Client user partition label.', title='User Id'
    )


class SearchResponse(BaseModel):
    """
    The flat results envelope — episodes and facts interleaved by score (api-design §3).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    results: list[SearchResult] = Field(
        ..., description='Typed hits, highest score first.', title='Results'
    )


class SyncAddResponse(BaseModel):
    """
    The 200 sync-write body: the turn plus the inline consolidation report (ADR 0004).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    consolidation: TesseraApiV1MemoriesConsolidationSummary = Field(
        ..., description='What the inline consolidation produced.'
    )
    turn_id: str = Field(..., description="The turn's client/ULID id.", title='Turn Id')


class RecallResourcesResponse(BaseModel):
    """
    The recall envelope: matched resources, highest similarity first (api-design §3).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    results: list[RecalledResource] = Field(
        ..., description='Matched resources, best-first.', title='Results'
    )
